name: Pull Request CI Checker
on:
  pull_request:

jobs:
  CI-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 30
        name: CI wait time
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const message = "Hello!";
            // Create error.
            process.exit(1)
            return message
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
